# .travis.yml for Elixir, https://github.com/bootlin/elixir
language: python

os:
  - linux

dist:
  - bionic

python:
  - "3.6"

before_install:
  - sudo apt-get -y install libdb-dev python3-pytest libjansson4
  - pip install jinja2 pygments bsddb3 falcon
  - wget https://bootlin.com/pub/elixir/universal-ctags_0+git20200526-0ubuntu1_amd64.deb
  - sudo dpkg -i universal-ctags_0+git20200526-0ubuntu1_amd64.deb

script:
  - prove -v
